### ISSUE TITLE
Testing sacc is always 0.0000, what's wrong?

### ISSUE THREAD

**Issue by Jeremy-lf** [whywhs/Pytorch-Handwritten-Mathematical-Expression-Recognition#6]
epoch is 0, lr rate is 0.00010, te is 1.000, batch_size is 6, loading for 97.619%, running_loss is 39.947078
epoch is 0, lr rate is 0.00010, te is 1.000, batch_size is 6, loading for 99.055%, running_loss is 37.357895
epoch is 0, the whole loss is 43.131678
Now, begin testing!!
total_line_rec is 0
wer is 0.70824
sacc is 0.00000 
the best is 0.000000
the loss is bigger than before,so do not save the model

**Comment by whywhs** [comment]
As the loss is big, the first few epochs will be 0 in sacc. You can see my training log file. test_right_SGD_bs8_te1_mask_conv_bn_b_dr05.txt
So, I suggest you train more epochs

**Comment by Jeremy-lf** [comment]
> As the loss is big, the first few epochs will be 0 in sacc. You can see my training log file. test_right_SGD_bs8_te1_mask_conv_bn_b_dr05.txt
> So, I suggest you train more epochs

thank u ,today  i have encounter another problem ,when i use Multi-GPUs, i set gpu =[0,1,2],it will show  the erro:
RuntimeError: shape '[0, 256]' is invalid for input of size 256

when i use one gpu ,it will show the error :
RuntimeError: CUDA out of memory. Tried to allocate 3.88 MiB  -###batch_size is 4
the first epoch is normal ,when it go 2 or 3 epoch ,it will have a error

so ,what should i do to solve these problems ?

**Comment by whywhs** [comment]
As your batch size is too big, you will get this error "CUDA out of memory" . So, please use small batch size or use more GPU.  
If you get this error after a few epochs (I also met this error before), I think this is because DenseNet's problems. DenseNet have a problem about using memory. So, I also suggest you 'down your epoch' and 'use more GPU'
Then, the number of batch size must be a multiple of GPU numbers.
